---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devservers.devservers.io
  resources:
  - devserverflavors
  - devservers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devservers.devservers.io
  resources:
  - devserverflavors/finalizers
  - devservers/finalizers
  verbs:
  - update
- apiGroups:
  - devservers.devservers.io
  resources:
  - devserverflavors/status
  - devservers/status
  verbs:
  - get
  - patch
  - update
