repos:
  - repo: local
    hooks:
      - id: uv-sync
        name: UV sync
        entry: uv sync
        language: system
        pass_filenames: false
        always_run: true
      - id: ruff
        name: Run ruff
        entry: uv run ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ty
        name: Run ty
        entry: uv run ty check src/
        language: system
        types: [python]
        pass_filenames: false
