repos:
  - repo: local
    hooks:
      - id: ruff
        name: Run ruff
        entry: uvx -p 3.13 ruff check --fix
        language: system
        types: [python]
        pass_filenames: false
      - id: ty
        name: Run ty
        entry: uvx -p 3.13 ty check src/
        language: system
        types: [python]
        pass_filenames: false