apiVersion: eks.amazonaws.com/v1
kind: NodePool
metadata:
  name: gpu-accelerated
spec:
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 10m
  nodeClass:
    ref:
      name: default
  taints:
    - key: nvidia.com/gpu
      value: "true"
      effect: NoSchedule
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - g6e.xlarge
        - g6e.2xlarge
        - g6e.4xlarge
        - g6e.8xlarge
        - g6.xlarge
        - g6.2xlarge
        - g6.4xlarge
        - g6.8xlarge
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - on-demand
