apiVersion: v1
kind: Service
metadata:
  name: bastion
  namespace: devserver-bastion
  labels:
    app: bastion
    component: bastion
    phase: "1"
  annotations:
    # AWS Load Balancer annotations for production
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
    service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
    # Enable connection draining
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-enabled: "true"
    service.beta.kubernetes.io/aws-load-balancer-connection-draining-timeout: "60"
    
    # Health check settings
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "10"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-timeout: "5"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    
spec:
  type: LoadBalancer
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hour session affinity
  
  ports:
  - name: ssh
    port: 22
    targetPort: 22
    protocol: TCP
  
  selector:
    app: bastion

---
# ConfigMap for storing public information about the bastion
apiVersion: v1
kind: ConfigMap
metadata:
  name: bastion-info
  namespace: devserver-bastion
  labels:
    app: bastion
    component: bastion
    phase: "1"
data:
  phase: "1"
  version: "0.1.0-phase1"
  description: "PyTorch DevServer Platform Bastion - Phase 1"
  features: |
    - SSH access to bastion server
    - Basic devctl CLI (status, info, test-k8s)
    - Kubernetes connectivity testing
    - User namespace assignment
  
  coming_soon: |
    Phase 2:
    - DevServer creation and management
    - PyTorch development containers
    - Distributed training support
    - Full operator with CRDs
  
  usage: |
    1. SSH to bastion: ssh username@bastion.devservers.company.com
    2. Check status: devctl status
    3. Test connectivity: devctl test-k8s
    4. Get help: devctl info
