apiVersion: batch/v1
kind: Job
metadata:
  name: test-dynamic-large
  namespace: default
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: test-dynamic-large
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3  # Target H100 GPUs specifically
      containers:
      - name: large-workload
        image: ubuntu:20.04
        command:
        - /bin/bash
        - -c
        - |
          echo "=== Large Workload - 3g.40gb MIG Slice ==="
          echo "Requested: nvidia.com/mig-3g.40gb = 1"
          echo "Expected: ~40GB GPU memory"
          echo ""
          nvidia-smi || echo "nvidia-smi not available"
          echo ""
          echo "=== Environment ==="
          env | grep NVIDIA || echo "No NVIDIA env vars"
        resources:
          limits:
            nvidia.com/mig-3g.40gb: 1  # Large workload
          requests:
            nvidia.com/mig-3g.40gb: 1