apiVersion: batch/v1
kind: Job
metadata:
  name: test-coexist-small-1
spec:
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3  # Target H100 GPUs specifically
      containers:
      - name: workload
        image: ubuntu:20.04
        command: ["sleep", "30"]
        resources:
          limits:
            nvidia.com/mig-1g.10gb: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-coexist-small-2
spec:
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3  # Target H100 GPUs specifically
      containers:
      - name: workload
        image: ubuntu:20.04
        command: ["sleep", "30"]
        resources:
          limits:
            nvidia.com/mig-1g.10gb: 1
---
apiVersion: batch/v1
kind: Job
metadata:
  name: test-coexist-medium
spec:
  template:
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3  # Target H100 GPUs specifically
      containers:
      - name: workload
        image: ubuntu:20.04
        command: ["sleep", "30"]
        resources:
          limits:
            nvidia.com/mig-2g.20gb: 1