apiVersion: batch/v1
kind: Job
metadata:
  name: test-dynamic-full
  namespace: default
spec:
  completions: 1
  parallelism: 1
  backoffLimit: 3
  template:
    metadata:
      labels:
        app: test-dynamic-full
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        nvidia.com/gpu.product: NVIDIA-H100-80GB-HBM3  # Target H100 GPUs specifically
      containers:
      - name: full-workload
        image: ubuntu:20.04
        command:
        - /bin/bash
        - -c
        - |
          echo "=== Full GPU Workload ==="
          echo "Requested: nvidia.com/gpu = 1"
          echo "Expected: ~80GB GPU memory (full H100)"
          echo ""
          nvidia-smi || echo "nvidia-smi not available"
          echo ""
          echo "=== Environment ==="
          env | grep NVIDIA || echo "No NVIDIA env vars"
        resources:
          limits:
            nvidia.com/gpu: 1  # Full GPU
          requests:
            nvidia.com/gpu: 1