apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devserverflavors.devserver.io
spec:
  group: devserver.io
  names:
    kind: DevServerFlavor
    listKind: DevServerFlavorList
    plural: devserverflavors
    singular: devserverflavor
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                resources:
                  type: object
                  properties:
                    requests:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    limits:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                nodeSelector:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
