apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devserverusers.devserver.io
spec:
  group: devserver.io
  names:
    plural: devserverusers
    singular: devserveruser
    kind: DevServerUser
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                username:
                  type: string
                suspended:
                  type: boolean
              required:
                - username
