apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: devserverusers.devserver.io
spec:
  group: devserver.io
  names:
    kind: DevServerUser
    listKind: DevServerUserList
    plural: devserverusers
    singular: devserveruser
  scope: Cluster
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [username]
              properties:
                username:
                  type: string
                  maxLength: 63
                  pattern: '^[a-z0-9]([-a-z0-9]*[a-z0-9])?$'
                rbac:
                  type: object
                  properties:
                    additionalRoleRefs:
                      type: array
                      items:
                        type: object
                        required: [name, kind, apiGroup]
                        properties:
                          name:
                            type: string
                          namespace:
                            type: string
                          kind:
                            type: string
                            enum: [Role, ClusterRole]
                          apiGroup:
                            type: string
                quotas:
                  type: object
                  properties:
                    resourceQuotaSpec:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
                    limitRangeSpec:
                      type: object
                      x-kubernetes-preserve-unknown-fields: true
            status:
              type: object
              properties:
                phase:
                  type: string
                  enum: [Pending, Ready, Error]
                message:
                  type: string
                namespace:
                  type: string
                conditions:
                  type: array
                  items:
                    type: object
                    required: [type, status]
                    properties:
                      type:
                        type: string
                      status:
                        type: string
                      reason:
                        type: string
                      message:
                        type: string
                      lastTransitionTime:
                        type: string
                        format: date-time
